import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Separator } from "@/components/ui/separator";
import Image from "next/image";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  {
    name: "Projects",
    children: [
      {
        name: "All projects",
        href: "/projects",
      },
    ],
    href: "/projects",
  },
  {
    name: "RLS Policies",
    href: "/rls-policies",
  },
  {
    name: "Test Execution",
    href: "/test-execution",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen p-4 ">
          <div className="grid grid-cols-12 min-h-screen ">
            <div className="col-span-12 flex items-center sticky w-full justify-between border-b">
              <div className="border-r h-16 w-64 p-4 flex justify-between align-middle text-center">
                <Image src="/next.svg" alt="Logo" width={64} height={64} />
                <div className="font-bold text-xl ">Keyrxng</div>
              </div>
              <div className="col-span-12">
                <div className="flex justify-between items-center">
                  <div className="flex items-center">
                    <Button className="mr-4">Search</Button>
                    <Button className="mr-4">Notifications</Button>
                    <Button className="mr-4">Settings</Button>
                  </div>
                </div>
              </div>
            </div>

            <div className="ml-[265px] mt-16 absolute col-span-12 text-2xl font-bold">
              {children}
            </div>
            <div className="w-64 border-r h-screen p-4 ">
              <div className="flex flex-col">
                {navItems.map((item) => (
                  <a key={item.name} href={item.href} className=" mb-4">
                    {item.name}
                  </a>
                ))}
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
